# Generated by Django 5.2.7 on 2025-12-07 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('youtube_link', models.URLField()),
                ('sheet_music', models.FileField(blank=True, null=True, upload_to='sheet_music/')),
            ],
            options={
                'ordering': ['-year', 'name'],
            },
        ),
    ]
