# Generated by Django 5.2.7 on 2025-11-16 19:14

import gallery.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_remove_photo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=gallery.utils.photo_upload_path),
        ),
    ]
