# Generated by Django 5.2.7 on 2026-08-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('feature', 'Feature Request'), ('bug', 'Bug Report'), ('question', 'General Question'), ('gdpr_data', 'Request Personal Data'), ('gdpr_delete', 'Request Data Deletion'), ('other', 'Other')], max_length=20)),
                ('message', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
            ],
        ),
    ]
