# Generated by Django 5.2.7 on 2025-11-22 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_puzzles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='description',
        ),
    ]
