# Generated by Django 5.2.7 on 2026-08-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizGenerationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('topic', models.TextField(blank=True)),
                ('level', models.CharField(blank=True, max_length=50)),
                ('no_of_questions', models.IntegerField()),
                ('no_of_choices', models.IntegerField()),
                ('additional_info', models.TextField(blank=True)),
                ('quiz_type', models.CharField(max_length=50)),
                ('file_uploaded', models.BooleanField(default=False)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
            ],
        ),
    ]
