# Generated by Django 5.2.7 on 2026-03-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_alter_module_slug_alter_subject_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_quizzable',
            field=models.BooleanField(default=False),
        ),
    ]
