# Generated by Django 5.2.7 on 2025-11-11 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_alter_subject_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='subject',
        ),
    ]
