# Generated by Django 5.2.7 on 2026-03-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_document_is_quizzable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='is_quizzable',
            field=models.BooleanField(default=True),
        ),
    ]
